import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider"; 
import { CurrencyProvider } from "@/context/CurrencyContext";
import Navbar from "@/components/ui/navbar"; // ✅ Import Navbar
import Footer from "@/components/ui/footer"; // ✅ Import Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vendora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CurrencyProvider>
      <ClientProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {/* ✅ Add Navbar Here */}
            <Navbar />

            {/* ✅ Wrap children inside a main container */}
            <main className="min-h-screen flex flex-col">{children}</main>

            {/* ✅ Add Footer Here */}
            <Footer />
          </body>
        </html>
      </ClientProvider>
    </CurrencyProvider>
  );
}
